on:
  workflow_dispatch:
jobs:
  demo_app_authentication:
    runs-on: ubuntu-latest
    env: 
      ORG_NAME: PixelBayStudios
      REPO: TokenTest
    steps:
      - name: Generate a GitHub App installation access tokens
        id: generate-token
        # When repositories is not set, creates a token for all repositories for ORG_NAME
        # Token lasts for 1 hour
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ vars.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: ${{ env.ORG_NAME }}

      - name: Generate Release notes
        id: get_release_notes
        #https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ env.ORG_NAME }}/${{ env.REPO }}/releases/generate-notes
          tag_name: test # note: will show as an error "Invalid action input", disregard
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - run: "echo release notes: '${{ fromJson(steps.get_release_notes.outputs.data).body }}'"
      - run: "echo token: '${{ steps.generate-token.outputs.token }}'"
      - run: echo STASIS_GH_TOKEN=${{ steps.generate-token.outputs.token }} >> $GITHUB_ENV